# Generated by Django 5.2.8 on 2025-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='year_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
